language: 'ruby'
env:
  - GMAIL_ADDRESS=picard@test.com
  - RAILS_ENV=test
rvm:
  - 2.3.3
services:
  - elasticsearch
script:
  - bundle exec rake --trace db:migratespec
  - bundle exec rspec
before_script:
  - sleep 10
  - psql -c 'create database picard_test' -U postgres
