language: 'ruby'
env:
  - GMAIL_ADDRESS=picard@test.com RAILS_ENV=test
rvm:
  - 2.3.3
services:
  - elasticsearch
before_script:
  - sleep 10
  - psql -c 'create database picard_test' -U postgres
  - bundle exec rake --trace db:migrate
script:
  - bundle exec rake rspec
