language: 'ruby'
dist: bionic
sudo: false
cache: bundler

env:
  - GMAIL_ADDRESS=picard@test.com RAILS_ENV=test

services:
  - elasticsearch
  - postgresql

before_script:
  - psql -c 'create database picard_test' -U postgres
  - bundle exec rake --trace db:migrate

script:
  - bundle exec rake spec
